spring:
  banner:
      location: classpath:banner.txt
  application:
    name: siscal-old-api-server
  datasource:
    url: jdbc:informix-sqli://192.168.0.110:9094/siscal_old:INFORMIXSERVER=ol_informix1410_local_siscal_old
    username: informix #ifxjson
    password: 12345
    driver-class-name: com.informix.jdbc.IfxDriver
      
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
#        jdbc.lob.non_contextual_creation: true
#        format_sql: true
        dialect: org.hibernate.dialect.Informix10Dialect
    open-in-view: false
        
server:
  port: 8065
